title IntendedRecipients SOAP + AMQP

Alert Pub->Alert Broker: Publish message in SOAP by specifying \n./s:Header/oh:intended-recpient and s:Body/oh:message\n \noptionally set @statusCode and @statusCodeScheme to allow\n Alert Cons to receive only certain status alerts


Alert Broker->Alert Pub:ACK (SOAP)


loop over oh:intended-recipient/oh:query-target  
Alert Broker->Human Reg: resolve recipients\nsend s:/Header\nnote: should allow for ability to cache\n/oh:inteneded-recipient/oh:target-query/*

Human Reg->Alert Broker:here  is what I was able to resolve oh:intended-recipient to 
Alert Broker->Alert Broker: put alert in queue with timestamp

end


Alert Cons->Alert Broker: HTTP GET\nGive me any alerts published since $timestamp on page $page\nand optional status $statusCode and $statusCodeScheme


Alert Broker->Alert Cons: HTTP reposnse\n return ATOM feed of oh:alert
note over Alert Cons:Can avoid carrying PHI by making use of oh:message/@src



loop OVER alert id.  RENDER CONTENT AND INTERACT WITH A HUMAN

Alert Cons->Alert Broker: ACK on alert id\nHTTP POST
Alert Broker->Alert Broker: remove alert from queue
note over Alert Broker: next request for ATOM feed will have changed atom:updated\nQuestion: what are ACKing?\n-that the AC took responsibility to deliver the message 

Alert Cons->Alert Cons: Fetch content from src@Series of Tubes 
Alert Cons->Alert Cons: Render 


Alert Cons->Human: deliver content





opt RECORD OUTCOME OF HUMAN INTERACTION
Human->Alert Cons:Register action\n (e.g. SDC)
note over Alert Cons: human interaction may trigger change in status



Alert Cons->Alert Reporter: HTTP POST\nATOM PUBLISH?\ncontent  oh:alert-receipt

note over Alert Cons: response code could:\n-indicate "Yes, I saw someone with Ebola symptoms"\n-support ICP workflows\n\nsets @responseCode and @responseCodeScheme\n@timestamp and geo data

Alert Pub->Alert Reporter: check status of  $alert-id\n SOAP

Alert Reporter->Alert Pub: return status\nSOAP \ncontains s:Body/oh:alert-receipt
end
end

