title IntendedRecipients Alert Broker with Receipt Report

Alert Pub->Alert Broker: Publish oh:Alert message in\n \noptionally set @statusCode and @statusCodeScheme


Alert Broker->Alert Pub:ACK 


Alert Cons->Alert Broker: HTTP GET\nGive me an oh:alert \nAlert Cons can ask Alert Broker to resolve recipients or not
note over Alert Cons: should this be a single oh:alert or a feed of oh:alert's?\n \n(in the later allow querting on\n- $timestamp\n- $page\n- $statusCode and $statusCodeScheme\n 

opt [if Alert Cons want Alert Broker to resolve ]
loop over /oh:alert/oh:intended-recipient/oh:query-target  
Alert Broker->Human Reg: resolve recipients

Human Reg->Alert Broker:here  is what I was able to resolve oh:intended-recipient to 
Alert Broker->Alert Broker: replace the /oh:alert/oh-intended-necipieints/oh:query-target \n with list of oh:target's

end
end



Alert Broker->Alert Cons: HTTP response\n return ATOM feed of oh:alert / or a single feed
note over Alert Cons:Can avoid carrying PHI by making use of oh:message/@src



loop OVER alert id.  RENDER CONTENT AND INTERACT WITH A HUMAN

Alert Cons->Alert Broker: ACK on alert id\nHTTP POST
Alert Broker->Alert Broker: remove alert from queue
note over Alert Broker: the AC took responsibility to deliver the message 

Alert Cons->Alert Cons: Fetch content from src@Series of Tubes 
Alert Cons->Alert Cons: Render 


Alert Cons->Human: deliver content





opt RECORD OUTCOME OF HUMAN INTERACTION
Human->Alert Cons:Register action\n (e.g. SDC)
note over Alert Cons: human interaction may trigger change in status



Alert Cons->Alert Reporter: HTTP POST\nATOM PUBLISH?\ncontent  oh:alert-receipt

note over Alert Cons: response code could:\n-indicate "Yes, I saw someone with Ebola symptoms"\n-support ICP workflows\n\nsets @responseCode and @responseCodeScheme\n@timestamp and geo data

Alert Pub->Alert Reporter: get oh:alert-receipt's for a given  $alert-id

Alert Reporter->Alert Pub: atom feed of oh:alert-receipt's
end
end

